apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rssbot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rssbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rssbot
  template:
    metadata:
      labels:
        app: rssbot
    spec:
      containers:
        - name: rssbot
          image: ghcr.io/supu2/rssbot:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: XMPP_HOST
              valueFrom:
                secretKeyRef:
                  name: rssbot-creds
                  key: xmpp-host
            - name: XMPP_PORT
              value: "5222"
            - name: XMPP_JID
              valueFrom:
                secretKeyRef:
                  name: rssbot-creds
                  key: xmpp-username
            - name: XMPP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rssbot-creds
                  key: xmpp-password
            - name: RSS_POLL_INTERVAL
              value: "600"
            - name: RSS_USER_AGENT
              value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:146.0) Gecko/20100101 Firefox/146.0"
            - name: DB_TYPE
              value: "sqlite"
            - name: DB_PATH
              value: "/data/rss.db"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rssbot-pvc
